#! /bin/bash
[ -f ./Snapshots.json.old ] && mv ./Snapshots.json.old ./Snapshots.json.older
[ -f ./Snapshots.json ] && mv ./Snapshots.json ./Snapshots.json.old

aws ec2 describe-snapshots --owner-ids 193583157031  --query 'Snapshots[].[SnapshotId,StartTime,VolumeSize,Description,Tags[?Key==`Name`].Value,Tags[?Key==`Triggered`].Value]' --output json > Snapshots.json

#aws ec2 describe-snapshots --owner-ids 193583157031  --query 'Snapshots[].[SnapshotId,StartTime,VolumeId,VolumeSize,Tags[?Key==`Name`].Value]' --output json > Snapshots.json
